# This file compiled from .travis.yml.in

sudo: required

language: python

python:
  - "3.6.6"

services:
  - docker

env:
  - BASE_DOCKER_ON_TRAVIS=true

cache:
  pip: true

install:
  # Install Python dependencies
  - python -m pip install --upgrade pip==18.0
  - python -m pip install -r requirements3.txt

  # Install Docker and Docker-Compose
  - sudo add-apt-repository "deb https://apt.dockerproject.org/repo ubuntu-trusty main"
  - sudo apt-get update
  - apt-cache policy docker-engine
  - docker version
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install --yes --force-yes docker-engine=1.11.2-0~trusty
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.8.0-rc1/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker version
  - docker-compose version

  # Invoke will get our other dependencies
  - invoke dependencies_ensure

  # Build our Dockerfiles  - docker build -f Dockerfile .
script:
  - |
    invoke docker_start
    sleep 60
  - nosetests tests.fast
  - nosetests
